### PR TITLE
Added Typescript support with rules

### PR DESCRIPTION
**Pull request by lukebrobbs**
- Enabled rules following React COP meeting 
- Created `tsconfig` file to allow creation of `.ts` files for testing
- Updated parser options to point at new `tsconfig` file
- Added new dependency to allow parsing of `ts` files with `eslint`

### CODE REVIEW

**Comment by lukebrobbs** [comment]
I just know this will be the one :star:

**Comment by mikeskaife** [comment]
package.json - for the lint npm script, do we write any tests in .ts or are they all .js? file path will need updating for test files if not just .js

tsconfig - are we not ES6? Should target be set to 2016 rather than ES5?

package.json - pedantic, but can we remove the ^ from package version numbers and keep them at a specific number?

**Comment by lukebrobbs** [comment]
All tests in this repo are .js I believe. Other projects using this package have their own lint script which targets the correct files.

It would make sense to set the target to es6 yeah

I’ll change it up when I get a moment 👌

**Comment by lukebrobbs** [comment]
I've removed the ^ from the `package.json`

Also updated the target in the `tsConfig.json` to "ES2016"

I've also removed the rule that enforces users prefix a Typescript interface with an 'I', the [Microsoft Coding guidelines](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines) do not recommend

**Comment by lukebrobbs** [comment]
I know the guidelines are for contributors to Typescript, feel free to add it back in if you feel it will benefit us

**Pull request merged**
